/* Editorial metadata for constants.txt. Bounds supplement engine parsing. */
static const char *anybandui_tuning_schema =
"[{\"id\":\"level-max:monsters\",\"group\":\"level-max\",\"label\":\"Monsters per level\",\"description\":\"Maximum number of monsters on the level\",\"minimum\":1024,\"maximum\":4096,\"structural\":true"
",\"category\":\"Monsters\",\"tier\":false,\"advanced\":true},{\"id\":\"mon-gen:chance\",\"group\":\"mon-gen\",\"label\":\"New monster interval\",\"description\":\"1/per-turn-chance of new monster generat"
"ion\",\"minimum\":1,\"maximum\":60000,\"structural\":false,\"category\":\"Monsters\",\"tier\":false,\"advanced\":false},{\"id\":\"mon-gen:level-min\",\"group\":\"mon-gen\",\"label\":\"Starting monster popul"
"ation\",\"description\":\"Minimum number of monsters generated on a level\",\"minimum\":0,\"maximum\":100,\"structural\":false,\"category\":\"Monsters\",\"tier\":false,\"advanced\":false},{\"id\":\"mon-"
"gen:town-day\",\"group\":\"mon-gen\",\"label\":\"Daytime townsfolk\",\"description\":\"Number of townsfolk generated in the day\",\"minimum\":0,\"maximum\":100,\"structural\":false,\"category\":\"Monste"
"rs\",\"tier\":false,\"advanced\":false},{\"id\":\"mon-gen:town-night\",\"group\":\"mon-gen\",\"label\":\"Nighttime townsfolk\",\"description\":\"Number of townsfolk generated in the night\",\"minimum\":0"
",\"maximum\":100,\"structural\":false,\"category\":\"Monsters\",\"tier\":false,\"advanced\":false},{\"id\":\"mon-gen:repro-max\",\"group\":\"mon-gen\",\"label\":\"Breeding population limit\",\"description\""
":\"Maximum number of breeding monsters allowed on a level\",\"minimum\":0,\"maximum\":500,\"structural\":false,\"category\":\"Monsters\",\"tier\":false,\"advanced\":false},{\"id\":\"mon-gen:ood-chanc"
"e\",\"group\":\"mon-gen\",\"label\":\"Out-of-depth monster chance\",\"description\":\"Chance of a generated monster's level being inflated is one-in-this\",\"minimum\":1,\"maximum\":10000,\"structur"
"al\":false,\"category\":\"Monsters\",\"tier\":false,\"advanced\":false},{\"id\":\"mon-gen:ood-amount\",\"group\":\"mon-gen\",\"label\":\"Out-of-depth monster levels\",\"description\":\"Maximum out-of-dept"
"h amount for monster generation\",\"minimum\":0,\"maximum\":50,\"structural\":false,\"category\":\"Monsters\",\"tier\":false,\"advanced\":false},{\"id\":\"mon-gen:group-max\",\"group\":\"mon-gen\",\"label"
"\":\"Maximum group size\",\"description\":\"Maximum number of monsters in a group\",\"minimum\":1,\"maximum\":100,\"structural\":false,\"category\":\"Monsters\",\"tier\":false,\"advanced\":false},{\"id\""
":\"mon-gen:group-dist\",\"group\":\"mon-gen\",\"label\":\"Related group distance\",\"description\":\"Maximum distance of a group of monsters from a related group\",\"minimum\":1,\"maximum\":20,\"stru"
"ctural\":false,\"category\":\"Monsters\",\"tier\":false,\"advanced\":false},{\"id\":\"mon-play:break-glyph\",\"group\":\"mon-play\",\"label\":\"Rune of protection strength\",\"description\":\"Rune of prot"
"ection resistance to monster breaking\",\"minimum\":1,\"maximum\":10000,\"structural\":false,\"category\":\"Monsters\",\"tier\":false,\"advanced\":false},{\"id\":\"mon-play:mult-rate\",\"group\":\"mon-p"
"lay\",\"label\":\"Breeding interval\",\"description\":\"High value slows multiplication\",\"minimum\":1,\"maximum\":1000,\"structural\":false,\"category\":\"Monsters\",\"tier\":false,\"advanced\":false},"
"{\"id\":\"mon-play:life-drain\",\"group\":\"mon-play\",\"label\":\"Experience drained per hit (%)\",\"description\":\"Percent of player exp drained per hit\",\"minimum\":0,\"maximum\":100,\"structural\""
":false,\"category\":\"Monsters\",\"tier\":false,\"advanced\":false},{\"id\":\"mon-play:flee-range\",\"group\":\"mon-play\",\"label\":\"Fleeing distance beyond sight\",\"description\":\"Monsters will run "
"up to this many grids out of sight\",\"minimum\":1,\"maximum\":30,\"structural\":false,\"category\":\"Monsters\",\"tier\":false,\"advanced\":false},{\"id\":\"mon-play:turn-range\",\"group\":\"mon-play\","
"\"label\":\"Cornered monster turn distance\",\"description\":\"Terrified monsters will turn to fight if they are slower than the character, and closer than this distance.\",\"minimum\":1,\"ma"
"ximum\":30,\"structural\":false,\"category\":\"Monsters\",\"tier\":false,\"advanced\":false},{\"id\":\"dun-gen:cent-max\",\"group\":\"dun-gen\",\"label\":\"Room centre capacity\",\"description\":\"Number of"
" possible room centres (and hence rooms) on a normal level\",\"minimum\":100,\"maximum\":500,\"structural\":false,\"category\":\"World & generation\",\"tier\":false,\"advanced\":true},{\"id\":\"dun-"
"gen:door-max\",\"group\":\"dun-gen\",\"label\":\"Door candidate capacity\",\"description\":\"Number of possible door locations\",\"minimum\":200,\"maximum\":1000,\"structural\":false,\"category\":\"Worl"
"d & generation\",\"tier\":false,\"advanced\":true},{\"id\":\"dun-gen:wall-max\",\"group\":\"dun-gen\",\"label\":\"Wall piercing capacity\",\"description\":\"Number of possible places to pierce room wa"
"lls with tunnels\",\"minimum\":500,\"maximum\":2000,\"structural\":false,\"category\":\"World & generation\",\"tier\":false,\"advanced\":true},{\"id\":\"dun-gen:tunn-max\",\"group\":\"dun-gen\",\"label\":\""
"Tunnel grid capacity\",\"description\":\"Number of tunnel grids\",\"minimum\":900,\"maximum\":4000,\"structural\":false,\"category\":\"World & generation\",\"tier\":false,\"advanced\":true},{\"id\":\"du"
"n-gen:amt-room\",\"group\":\"dun-gen\",\"label\":\"Objects in rooms\",\"description\":\"Average number of objects to place in rooms\",\"minimum\":0,\"maximum\":100,\"structural\":false,\"category\":\"Wo"
"rld & generation\",\"tier\":false,\"advanced\":false},{\"id\":\"dun-gen:amt-item\",\"group\":\"dun-gen\",\"label\":\"Objects across the level\",\"description\":\"Average number of objects to place in "
"rooms/corridors\",\"minimum\":0,\"maximum\":100,\"structural\":false,\"category\":\"World & generation\",\"tier\":false,\"advanced\":false},{\"id\":\"dun-gen:amt-gold\",\"group\":\"dun-gen\",\"label\":\"Tre"
"asure across the level\",\"description\":\"Average amount of treasure to place in rooms/corridors\",\"minimum\":0,\"maximum\":100,\"structural\":false,\"category\":\"World & generation\",\"tier\":f"
"alse,\"advanced\":false},{\"id\":\"dun-gen:pit-max\",\"group\":\"dun-gen\",\"label\":\"Pits and nests per level\",\"description\":\"Maximum number of pits or nests allowed per level\",\"minimum\":0,\"m"
"aximum\":10,\"structural\":false,\"category\":\"World & generation\",\"tier\":false,\"advanced\":false},{\"id\":\"world:max-depth\",\"group\":\"world\",\"label\":\"Maximum dungeon depth\",\"description\":\""
"Maximum dungeon level; must be at least 100. Setting it below 128 may prevent the creation of some objects.\",\"minimum\":128,\"maximum\":128,\"structural\":false,\"category\":\"World & gene"
"ration\",\"tier\":false,\"advanced\":true},{\"id\":\"world:day-length\",\"group\":\"world\",\"label\":\"Day length\",\"description\":\"Number of turns from dawn to dawn\",\"minimum\":100,\"maximum\":30000,"
"\"structural\":false,\"category\":\"World & generation\",\"tier\":false,\"advanced\":false},{\"id\":\"world:dungeon-hgt\",\"group\":\"world\",\"label\":\"Dungeon height (tiles)\",\"description\":\"Max numb"
"er of grids in each dungeon level (vertically)\",\"minimum\":66,\"maximum\":99,\"structural\":true,\"category\":\"World & generation\",\"tier\":false,\"advanced\":false},{\"id\":\"world:dungeon-wid\""
",\"group\":\"world\",\"label\":\"Dungeon width (tiles)\",\"description\":\"Max number of grids in each dungeon level (horizontally)\",\"minimum\":198,\"maximum\":240,\"structural\":true,\"category\":\""
"World & generation\",\"tier\":false,\"advanced\":false},{\"id\":\"world:town-hgt\",\"group\":\"world\",\"label\":\"Town height (tiles)\",\"description\":\"Max number of grids in each town level (verti"
"cally)\",\"minimum\":22,\"maximum\":44,\"structural\":true,\"category\":\"World & generation\",\"tier\":false,\"advanced\":false},{\"id\":\"world:town-wid\",\"group\":\"world\",\"label\":\"Town width (tiles"
")\",\"description\":\"Max number of grids in each town level (horizontally)\",\"minimum\":66,\"maximum\":132,\"structural\":true,\"category\":\"World & generation\",\"tier\":false,\"advanced\":false}"
",{\"id\":\"world:feeling-total\",\"group\":\"world\",\"label\":\"Feeling squares per level\",\"description\":\"Total number of feeling squares per level\",\"minimum\":10,\"maximum\":300,\"structural\":f"
"alse,\"category\":\"World & generation\",\"tier\":false,\"advanced\":false},{\"id\":\"world:feeling-need\",\"group\":\"world\",\"label\":\"Squares needed for a feeling\",\"description\":\"Squares needed "
"to see to get first feeling\",\"minimum\":1,\"maximum\":300,\"structural\":false,\"category\":\"World & generation\",\"tier\":false,\"advanced\":false},{\"id\":\"world:stair-skip\",\"group\":\"world\",\"l"
"abel\":\"Levels travelled per staircase\",\"description\":\"Number of levels for each stair\",\"minimum\":1,\"maximum\":10,\"structural\":false,\"category\":\"World & generation\",\"tier\":false,\"adv"
"anced\":false},{\"id\":\"world:move-energy\",\"group\":\"world\",\"label\":\"Energy per movement\",\"description\":\"Energy needed by player or monsters to move\",\"minimum\":100,\"maximum\":100,\"struc"
"tural\":false,\"category\":\"World & generation\",\"tier\":false,\"advanced\":true},{\"id\":\"carry-cap:pack-size\",\"group\":\"carry-cap\",\"label\":\"Pack slots\",\"description\":\"Max number of pack sl"
"ots for carrying inventory\",\"minimum\":1,\"maximum\":26,\"structural\":true,\"category\":\"Player & inventory\",\"tier\":false,\"advanced\":false},{\"id\":\"carry-cap:quiver-size\",\"group\":\"carry-c"
"ap\",\"label\":\"Quiver slots\",\"description\":\"Max number of quiver slots for carrying missiles\",\"minimum\":1,\"maximum\":10,\"structural\":true,\"category\":\"Player & inventory\",\"tier\":false,"
"\"advanced\":false},{\"id\":\"carry-cap:quiver-slot-size\",\"group\":\"carry-cap\",\"label\":\"Missiles per quiver slot\",\"description\":\"Max number of missiles per quiver slot\",\"minimum\":1,\"maxi"
"mum\":99,\"structural\":true,\"category\":\"Player & inventory\",\"tier\":false,\"advanced\":false},{\"id\":\"carry-cap:thrown-quiver-mult\",\"group\":\"carry-cap\",\"label\":\"Thrown-item quiver cost\","
"\"description\":\"For computing quiver capacity, is the multiplier for non-ammo thrown items\",\"minimum\":1,\"maximum\":40,\"structural\":true,\"category\":\"Player & inventory\",\"tier\":false,\""
"advanced\":false},{\"id\":\"carry-cap:floor-size\",\"group\":\"carry-cap\",\"label\":\"Objects per floor tile\",\"description\":\"Maximum number of objects allowed in a single dungeon grid.  The m"
"ain screen originally had a minimum size of 24 rows, so it could always display 23 objects + 1 header line.\",\"minimum\":1,\"maximum\":26,\"structural\":true,\"category\":\"Player & invento"
"ry\",\"tier\":false,\"advanced\":false},{\"id\":\"store:inven-max\",\"group\":\"store\",\"label\":\"Shop inventory slots\",\"description\":\"Maximum number of discrete objects in store inventory\",\"min"
"imum\":1,\"maximum\":40,\"structural\":true,\"category\":\"Shops & items\",\"tier\":false,\"advanced\":false},{\"id\":\"store:turns\",\"group\":\"store\",\"label\":\"Shop turnover interval\",\"description\":"
"\"Number of turns between turnovers\",\"minimum\":1,\"maximum\":30000,\"structural\":false,\"category\":\"Shops & items\",\"tier\":false,\"advanced\":false},{\"id\":\"store:shuffle\",\"group\":\"store\",\""
"label\":\"Shopkeeper replacement chance\",\"description\":\"1/Chance (per day) of an owner changing\",\"minimum\":1,\"maximum\":10000,\"structural\":false,\"category\":\"Shops & items\",\"tier\":fals"
"e,\"advanced\":false},{\"id\":\"store:magic-level\",\"group\":\"store\",\"label\":\"Shop item enchantment level\",\"description\":\"Dungeon level to apply magic to objects for normal stores\",\"minim"
"um\":0,\"maximum\":100,\"structural\":false,\"category\":\"Shops & items\",\"tier\":false,\"advanced\":false},{\"id\":\"obj-make:max-depth\",\"group\":\"obj-make\",\"label\":\"Maximum item allocation dept"
"h\",\"description\":\"Maximum depth used in object allocation\",\"minimum\":100,\"maximum\":100,\"structural\":false,\"category\":\"Shops & items\",\"tier\":false,\"advanced\":true},{\"id\":\"obj-make:g"
"reat-obj\",\"group\":\"obj-make\",\"label\":\"Exceptional item chance\",\"description\":\"1/chance of inflating the requested object level\",\"minimum\":1,\"maximum\":10000,\"structural\":false,\"cate"
"gory\":\"Shops & items\",\"tier\":false,\"advanced\":false},{\"id\":\"obj-make:great-ego\",\"group\":\"obj-make\",\"label\":\"Exceptional ego item chance\",\"description\":\"1/chance of inflating the re"
"quested ego item level\",\"minimum\":1,\"maximum\":10000,\"structural\":false,\"category\":\"Shops & items\",\"tier\":false,\"advanced\":false},{\"id\":\"obj-make:fuel-torch\",\"group\":\"obj-make\",\"lab"
"el\":\"Maximum torch fuel\",\"description\":\"Maximum amount of fuel in a torch\",\"minimum\":1,\"maximum\":30000,\"structural\":false,\"category\":\"Shops & items\",\"tier\":false,\"advanced\":false},"
"{\"id\":\"obj-make:fuel-lamp\",\"group\":\"obj-make\",\"label\":\"Maximum lantern fuel\",\"description\":\"Maximum amount of fuel in a lantern\",\"minimum\":1,\"maximum\":30000,\"structural\":false,\"cat"
"egory\":\"Shops & items\",\"tier\":false,\"advanced\":false},{\"id\":\"obj-make:default-lamp\",\"group\":\"obj-make\",\"label\":\"Starting lantern fuel\",\"description\":\"Default amount of fuel in a la"
"ntern\",\"minimum\":0,\"maximum\":30000,\"structural\":false,\"category\":\"Shops & items\",\"tier\":false,\"advanced\":false},{\"id\":\"player:max-sight\",\"group\":\"player\",\"label\":\"Maximum sight dis"
"tance\",\"description\":\"Maximum visual range\",\"minimum\":1,\"maximum\":20,\"structural\":false,\"category\":\"Player & inventory\",\"tier\":false,\"advanced\":false},{\"id\":\"player:max-range\",\"gro"
"up\":\"player\",\"label\":\"Maximum spell and missile range\",\"description\":\"Maximum missile and spell range\",\"minimum\":1,\"maximum\":20,\"structural\":false,\"category\":\"Player & inventory\",\""
"tier\":false,\"advanced\":false},{\"id\":\"player:start-gold\",\"group\":\"player\",\"label\":\"Starting wealth\",\"description\":\"Amount of gold (or value of equipment) the player starts with\",\"mi"
"nimum\":0,\"maximum\":60000,\"structural\":false,\"category\":\"Player & inventory\",\"tier\":false,\"advanced\":false},{\"id\":\"player:food-value\",\"group\":\"player\",\"label\":\"Food duration\",\"descr"
"iption\":\"Number of turns that 1% of player food capacity feeds them for\",\"minimum\":1,\"maximum\":10000,\"structural\":false,\"category\":\"Player & inventory\",\"tier\":false,\"advanced\":fals"
"e},{\"id\":\"melee-critical:debuff-toh\",\"group\":\"melee-critical\",\"label\":\"Penalty to accuracy\",\"description\":\"Amount added to the to-hit value for calculating the chance of a melee cr"
"itical when the target is debuffed\",\"minimum\":0,\"maximum\":100,\"structural\":false,\"category\":\"Advanced combat\",\"tier\":false,\"advanced\":true},{\"id\":\"melee-critical:chance-weight-scal"
"e\",\"group\":\"melee-critical\",\"label\":\"Chance weight scale\",\"description\":\"Scale factor for the weapon's weight in the chance for a melee critical\",\"minimum\":0,\"maximum\":100,\"structu"
"ral\":false,\"category\":\"Advanced combat\",\"tier\":false,\"advanced\":true},{\"id\":\"melee-critical:chance-toh-scale\",\"group\":\"melee-critical\",\"label\":\"Chance accuracy scale\",\"description\""
":\"Scale factor for the overall to-hit value when calculating the chance for a melee critical\",\"minimum\":0,\"maximum\":100,\"structural\":false,\"category\":\"Advanced combat\",\"tier\":false"
",\"advanced\":true},{\"id\":\"melee-critical:chance-level-scale\",\"group\":\"melee-critical\",\"label\":\"Chance level scale\",\"description\":\"Scale factor for player level when calculating the "
"chance for a melee critical\",\"minimum\":0,\"maximum\":100,\"structural\":false,\"category\":\"Advanced combat\",\"tier\":false,\"advanced\":true},{\"id\":\"melee-critical:chance-toh-skill-scale\",\""
"group\":\"melee-critical\",\"label\":\"Chance accuracy skill scale\",\"description\":\"Scale factor for the to-hit skill when calculating the chance for a melee critical\",\"minimum\":0,\"maximu"
"m\":100,\"structural\":false,\"category\":\"Advanced combat\",\"tier\":false,\"advanced\":true},{\"id\":\"melee-critical:chance-offset\",\"group\":\"melee-critical\",\"label\":\"Chance offset\",\"descript"
"ion\":\"Value added to the chance for a melee critical\",\"minimum\":-10000,\"maximum\":10000,\"structural\":false,\"category\":\"Advanced combat\",\"tier\":false,\"advanced\":true},{\"id\":\"melee-cr"
"itical:chance-range\",\"group\":\"melee-critical\",\"label\":\"Chance range\",\"description\":\"Maximum range for melee critical chance; if the chance is N and the maximum range is M, then the"
" probability a critical will happen is min(max(0, N), M) / M; to avoid extra inaccuracies for the damage shown within object descriptions, this should be a multiple of 100\",\"minimu"
"m\":100,\"maximum\":1000000,\"structural\":false,\"category\":\"Advanced combat\",\"tier\":false,\"advanced\":true},{\"id\":\"melee-critical:power-weight-scale\",\"group\":\"melee-critical\",\"label\":\"P"
"ower weight scale\",\"description\":\"Scale factor for the weapon weight in the power of a melee critical\",\"minimum\":0,\"maximum\":100,\"structural\":false,\"category\":\"Advanced combat\",\"ti"
"er\":false,\"advanced\":true},{\"id\":\"melee-critical:power-random\",\"group\":\"melee-critical\",\"label\":\"Power random\",\"description\":\"The maximum of the random part of the power for a mele"
"e critical\",\"minimum\":1,\"maximum\":10000,\"structural\":false,\"category\":\"Advanced combat\",\"tier\":false,\"advanced\":true},{\"id\":\"melee-critical-level:0\",\"group\":\"melee-critical-level\","
"\"label\":\"Tier 1\",\"description\":\"Define each of the levels for melee criticals.  If no critical levels are defined, then there's no extra damage due to critical hits. The first valu"
"e is the cutoff for the power.  Any critical which has a power less than that cutoff and is not covered by a lower power level will fall in that level.  The cutoff for the last lev"
"el is not used and that level will catch any criticals not caught by the previous levels.  To be valid, the cutoffs for all levels but the last must be in scrictly ascending order."
" The second value is the damage multiplier for that power level. The third value is the amount added to the damage for that power level. The fourth value is the name of the message"
", from list-messages.h, to use when a critical happens for that power level.\",\"minimum\":0,\"maximum\":10000,\"structural\":false,\"category\":\"Advanced combat\",\"tier\":true,\"advanced\":tru"
"e},{\"id\":\"melee-critical-level:1\",\"group\":\"melee-critical-level\",\"label\":\"Tier 2\",\"description\":\"\",\"minimum\":0,\"maximum\":10000,\"structural\":false,\"category\":\"Advanced combat\",\"tier"
"\":true,\"advanced\":true},{\"id\":\"melee-critical-level:2\",\"group\":\"melee-critical-level\",\"label\":\"Tier 3\",\"description\":\"\",\"minimum\":0,\"maximum\":10000,\"structural\":false,\"category\":\"A"
"dvanced combat\",\"tier\":true,\"advanced\":true},{\"id\":\"melee-critical-level:3\",\"group\":\"melee-critical-level\",\"label\":\"Tier 4\",\"description\":\"\",\"minimum\":0,\"maximum\":10000,\"structural"
"\":false,\"category\":\"Advanced combat\",\"tier\":true,\"advanced\":true},{\"id\":\"melee-critical-level:4\",\"group\":\"melee-critical-level\",\"label\":\"Tier 5\",\"description\":\"\",\"minimum\":0,\"maxim"
"um\":10000,\"structural\":false,\"category\":\"Advanced combat\",\"tier\":true,\"advanced\":true},{\"id\":\"ranged-critical:debuff-toh\",\"group\":\"ranged-critical\",\"label\":\"Penalty to accuracy\",\"d"
"escription\":\"Amount added to the to-hit value for calculating the chance of a ranged critical when the target is debuffed\",\"minimum\":0,\"maximum\":100,\"structural\":false,\"category\":\""
"Advanced combat\",\"tier\":false,\"advanced\":true},{\"id\":\"ranged-critical:chance-weight-scale\",\"group\":\"ranged-critical\",\"label\":\"Chance weight scale\",\"description\":\"Scale factor for t"
"he missile's weight in the chance for a ranged critical\",\"minimum\":0,\"maximum\":100,\"structural\":false,\"category\":\"Advanced combat\",\"tier\":false,\"advanced\":true},{\"id\":\"ranged-criti"
"cal:chance-toh-scale\",\"group\":\"ranged-critical\",\"label\":\"Chance accuracy scale\",\"description\":\"Scale factor for the overall to-hit value when calculating the chance for a ranged cr"
"itical\",\"minimum\":0,\"maximum\":100,\"structural\":false,\"category\":\"Advanced combat\",\"tier\":false,\"advanced\":true},{\"id\":\"ranged-critical:chance-level-scale\",\"group\":\"ranged-critical\""
",\"label\":\"Chance level scale\",\"description\":\"Scale factor for player level when calculating the chance for a ranged critical\",\"minimum\":0,\"maximum\":100,\"structural\":false,\"category"
"\":\"Advanced combat\",\"tier\":false,\"advanced\":true},{\"id\":\"ranged-critical:chance-launched-toh-skill-scale\",\"group\":\"ranged-critical\",\"label\":\"Chance launched accuracy skill scale\",\""
"description\":\"Scale factor for the launched to-hit skill when calculating the chance for a ranged critical when using a launcher\",\"minimum\":0,\"maximum\":100,\"structural\":false,\"cate"
"gory\":\"Advanced combat\",\"tier\":false,\"advanced\":true},{\"id\":\"ranged-critical:chance-thrown-toh-skill-scale\",\"group\":\"ranged-critical\",\"label\":\"Chance thrown accuracy skill scale\",\""
"description\":\"Scale factor for the thrown to-hit skill when calculating the chance for a ranged critical for a thrown object\",\"minimum\":0,\"maximum\":100,\"structural\":false,\"category"
"\":\"Advanced combat\",\"tier\":false,\"advanced\":true},{\"id\":\"ranged-critical:chance-offset\",\"group\":\"ranged-critical\",\"label\":\"Chance offset\",\"description\":\"Value added to the chance f"
"or a ranged critical\",\"minimum\":-10000,\"maximum\":10000,\"structural\":false,\"category\":\"Advanced combat\",\"tier\":false,\"advanced\":true},{\"id\":\"ranged-critical:chance-range\",\"group\":\"r"
"anged-critical\",\"label\":\"Chance range\",\"description\":\"Maximum range for ranged critical chance; if the chance is N and the maximum range is M, then the probability a critical will "
"happen is min(max(0, N), M) / M; to avoid extra inaccuracies for the damage shown within object descriptions, this should be a multiple of 100\",\"minimum\":100,\"maximum\":1000000,\"str"
"uctural\":false,\"category\":\"Advanced combat\",\"tier\":false,\"advanced\":true},{\"id\":\"ranged-critical:power-weight-scale\",\"group\":\"ranged-critical\",\"label\":\"Power weight scale\",\"descrip"
"tion\":\"Scale factor for the missle weight in the power of a ranged critical\",\"minimum\":0,\"maximum\":100,\"structural\":false,\"category\":\"Advanced combat\",\"tier\":false,\"advanced\":true}"
",{\"id\":\"ranged-critical:power-random\",\"group\":\"ranged-critical\",\"label\":\"Power random\",\"description\":\"The maximum of the random part of the power for a ranged critical\",\"minimum\":1"
",\"maximum\":10000,\"structural\":false,\"category\":\"Advanced combat\",\"tier\":false,\"advanced\":true},{\"id\":\"ranged-critical-level:0\",\"group\":\"ranged-critical-level\",\"label\":\"Tier 1\",\"des"
"cription\":\"Define each of the levels for ranged criticals.  If no critical levels are defined, then there's no extra damage due to critical hits. The first value is the cutoff for "
"the power.  Any critical which has a power less than that cutoff and is not covered by a lower power level will fall in that level.  The cutoff for the last level is not used and t"
"hat level will catch any criticals not caught by the previous levels.  To be valid, the cutoffs for all levels but the last must be in scrictly ascending order. The second value is"
" the damage multiplier for that power level. The third value is the amount added to the damage for that power level. The fourth value is the name of the message, from list-messages"
".h, to use when a critical happens for that power level.\",\"minimum\":0,\"maximum\":10000,\"structural\":false,\"category\":\"Advanced combat\",\"tier\":true,\"advanced\":true},{\"id\":\"ranged-cri"
"tical-level:1\",\"group\":\"ranged-critical-level\",\"label\":\"Tier 2\",\"description\":\"\",\"minimum\":0,\"maximum\":10000,\"structural\":false,\"category\":\"Advanced combat\",\"tier\":true,\"advanced\":"
"true},{\"id\":\"ranged-critical-level:2\",\"group\":\"ranged-critical-level\",\"label\":\"Tier 3\",\"description\":\"\",\"minimum\":0,\"maximum\":10000,\"structural\":false,\"category\":\"Advanced combat\","
"\"tier\":true,\"advanced\":true},{\"id\":\"o-melee-critical:debuff-toh\",\"group\":\"o-melee-critical\",\"label\":\"Penalty to accuracy\",\"description\":\"Amount added to the to-hit value for calcul"
"ating the power of a melee critical when the target is debuffed\",\"minimum\":0,\"maximum\":100,\"structural\":false,\"category\":\"Advanced combat\",\"tier\":false,\"advanced\":true},{\"id\":\"o-me"
"lee-critical:power-toh-scale-numerator\",\"group\":\"o-melee-critical\",\"label\":\"Power accuracy scale multiplier\",\"description\":\"The numerator for the scale factor applied to the combin"
"ed to-hit value to get the power of the critical\",\"minimum\":0,\"maximum\":100,\"structural\":false,\"category\":\"Advanced combat\",\"tier\":false,\"advanced\":true},{\"id\":\"o-melee-critical:po"
"wer-toh-scale-denominator\",\"group\":\"o-melee-critical\",\"label\":\"Power accuracy scale divisor\",\"description\":\"The denominator for the scale factor applied to the combined to-hit valu"
"e to get the power of the critical\",\"minimum\":1,\"maximum\":10000,\"structural\":false,\"category\":\"Advanced combat\",\"tier\":false,\"advanced\":true},{\"id\":\"o-melee-critical:chance-power-s"
"cale-numerator\",\"group\":\"o-melee-critical\",\"label\":\"Chance power scale multiplier\",\"description\":\"The scale factor for the critical's power in the numerator for the chance of the c"
"ritical\",\"minimum\":0,\"maximum\":100,\"structural\":false,\"category\":\"Advanced combat\",\"tier\":false,\"advanced\":true},{\"id\":\"o-melee-critical:chance-power-scale-denominator\",\"group\":\"o-"
"melee-critical\",\"label\":\"Chance power scale divisor\",\"description\":\"The scale factor for the critical's power in the denominator for the chance of the critical\",\"minimum\":1,\"maximu"
"m\":10000,\"structural\":false,\"category\":\"Advanced combat\",\"tier\":false,\"advanced\":true},{\"id\":\"o-melee-critical:chance-add-denominator\",\"group\":\"o-melee-critical\",\"label\":\"Chance ad"
"d divisor\",\"description\":\"Value of an added term in the denominator for the chance of a critical\",\"minimum\":1,\"maximum\":10000,\"structural\":false,\"category\":\"Advanced combat\",\"tier\""
":false,\"advanced\":true},{\"id\":\"o-melee-critical-level:0\",\"group\":\"o-melee-critical-level\",\"label\":\"Tier 1\",\"description\":\"Define each of the levels for melee criticals.  They are c"
"onsidered in the order they appear so it's convenient to put the least likely first.  If no critical levels are defined, then there's no extra damage due to critical hits. Except f"
"or the last level, one over the first value is the probability that this level occurs when none of the prior levels have been selected; the last level will always be used if none o"
"f the prior levels have been selected. The first value must be positive. The second value is the number of dice to add for the critical.  It must be non-negative. The third value i"
"s the name of the message, from list-messages.h, to use when a critical happens for that power level.\",\"minimum\":0,\"maximum\":10000,\"structural\":false,\"category\":\"Advanced combat\",\""
"tier\":true,\"advanced\":true},{\"id\":\"o-melee-critical-level:1\",\"group\":\"o-melee-critical-level\",\"label\":\"Tier 2\",\"description\":\"\",\"minimum\":0,\"maximum\":10000,\"structural\":false,\"cate"
"gory\":\"Advanced combat\",\"tier\":true,\"advanced\":true},{\"id\":\"o-melee-critical-level:2\",\"group\":\"o-melee-critical-level\",\"label\":\"Tier 3\",\"description\":\"\",\"minimum\":0,\"maximum\":10000"
",\"structural\":false,\"category\":\"Advanced combat\",\"tier\":true,\"advanced\":true},{\"id\":\"o-melee-critical-level:3\",\"group\":\"o-melee-critical-level\",\"label\":\"Tier 4\",\"description\":\"\",\"m"
"inimum\":0,\"maximum\":10000,\"structural\":false,\"category\":\"Advanced combat\",\"tier\":true,\"advanced\":true},{\"id\":\"o-melee-critical-level:4\",\"group\":\"o-melee-critical-level\",\"label\":\"Ti"
"er 5\",\"description\":\"\",\"minimum\":0,\"maximum\":10000,\"structural\":false,\"category\":\"Advanced combat\",\"tier\":true,\"advanced\":true},{\"id\":\"o-ranged-critical:debuff-toh\",\"group\":\"o-rang"
"ed-critical\",\"label\":\"Penalty to accuracy\",\"description\":\"Amount added to the to-hit value for calculating the power of a ranged critical when the target is debuffed\",\"minimum\":0,\""
"maximum\":100,\"structural\":false,\"category\":\"Advanced combat\",\"tier\":false,\"advanced\":true},{\"id\":\"o-ranged-critical:power-launched-toh-scale-numerator\",\"group\":\"o-ranged-critical\","
"\"label\":\"Power launched accuracy scale multiplier\",\"description\":\"The numerator for the scale factor applied to the combined to-hit value to get the power of the critical with a la"
"unched missile\",\"minimum\":0,\"maximum\":100,\"structural\":false,\"category\":\"Advanced combat\",\"tier\":false,\"advanced\":true},{\"id\":\"o-ranged-critical:power-launched-toh-scale-denominato"
"r\",\"group\":\"o-ranged-critical\",\"label\":\"Power launched accuracy scale divisor\",\"description\":\"The denominator for the scale factor applied to the combined to-hit value to get the p"
"ower of the critical with a launched missile\",\"minimum\":1,\"maximum\":10000,\"structural\":false,\"category\":\"Advanced combat\",\"tier\":false,\"advanced\":true},{\"id\":\"o-ranged-critical:pow"
"er-thrown-toh-scale-numerator\",\"group\":\"o-ranged-critical\",\"label\":\"Power thrown accuracy scale multiplier\",\"description\":\"The numerator for the scale factor applied to the combine"
"d to-hit value to get the power of the critical with a thrown missile; this and the denominator are currently set so thrown missiles get more criticals\",\"minimum\":0,\"maximum\":100,\""
"structural\":false,\"category\":\"Advanced combat\",\"tier\":false,\"advanced\":true},{\"id\":\"o-ranged-critical:power-thrown-toh-scale-denominator\",\"group\":\"o-ranged-critical\",\"label\":\"Power"
" thrown accuracy scale divisor\",\"description\":\"The denominator for the scale factor applied to the combined to-hit value to get the power of the critical with a thrown missile\",\"mi"
"nimum\":1,\"maximum\":10000,\"structural\":false,\"category\":\"Advanced combat\",\"tier\":false,\"advanced\":true},{\"id\":\"o-ranged-critical:chance-power-scale-numerator\",\"group\":\"o-ranged-crit"
"ical\",\"label\":\"Chance power scale multiplier\",\"description\":\"The scale factor for the critical's power in the numerator for the chance of the critical\",\"minimum\":0,\"maximum\":100,\"s"
"tructural\":false,\"category\":\"Advanced combat\",\"tier\":false,\"advanced\":true},{\"id\":\"o-ranged-critical:chance-power-scale-denominator\",\"group\":\"o-ranged-critical\",\"label\":\"Chance pow"
"er scale divisor\",\"description\":\"The scale factor for the critical's power in the denominator for the chance of the critical\",\"minimum\":1,\"maximum\":10000,\"structural\":false,\"catego"
"ry\":\"Advanced combat\",\"tier\":false,\"advanced\":true},{\"id\":\"o-ranged-critical:chance-add-denominator\",\"group\":\"o-ranged-critical\",\"label\":\"Chance add divisor\",\"description\":\"Value o"
"f an added term in the denominator for the chance of a critical\",\"minimum\":1,\"maximum\":10000,\"structural\":false,\"category\":\"Advanced combat\",\"tier\":false,\"advanced\":true},{\"id\":\"o-"
"ranged-critical-level:0\",\"group\":\"o-ranged-critical-level\",\"label\":\"Tier 1\",\"description\":\"Define each of the levels for ranged criticals.  They are considered in the order they ap"
"pear so it's convenient to put the least likely first.  If no critical levels are defined, then there's no extra damage due to critical hits. Except for the last level, one over th"
"e first value is the probability that this level occurs when none of the prior levels have been selected; the last level will always be used if none of the prior levels have been s"
"elected. The first value must be positive. The second value is the number of dice to add for the critical.  It must be non-negative. The third value is the name of the message, fro"
"m list-messages.h, to use when a critical happens for that power level.\",\"minimum\":0,\"maximum\":10000,\"structural\":false,\"category\":\"Advanced combat\",\"tier\":true,\"advanced\":true},{\""
"id\":\"o-ranged-critical-level:1\",\"group\":\"o-ranged-critical-level\",\"label\":\"Tier 2\",\"description\":\"\",\"minimum\":0,\"maximum\":10000,\"structural\":false,\"category\":\"Advanced combat\",\"tie"
"r\":true,\"advanced\":true},{\"id\":\"o-ranged-critical-level:2\",\"group\":\"o-ranged-critical-level\",\"label\":\"Tier 3\",\"description\":\"\",\"minimum\":0,\"maximum\":10000,\"structural\":false,\"categ"
"ory\":\"Advanced combat\",\"tier\":true,\"advanced\":true}]";
