# Isolate process-global mouse capture/cursor operations between native panels.
file(READ "${imgui_SOURCE_DIR}/backends/imgui_impl_sdl3.cpp" platform_backend)
function(platform_replace old new)
    string(FIND "${platform_backend}" "${old}" location)
    if(location EQUAL -1)
        message(FATAL_ERROR "Pinned ImGui SDL backend changed; review multi-window adaptation")
    endif()
    string(REPLACE "${old}" "${new}" platform_backend "${platform_backend}")
    set(platform_backend "${platform_backend}" PARENT_SCOPE)
endfunction()
platform_replace("if (bd->MouseCanUseCapture)" "if (bd->MouseCanUseCapture && SDL_GetKeyboardFocus() == bd->Window)")
platform_replace("    ImGuiMouseCursor imgui_cursor = ImGui::GetMouseCursor();" "    if (SDL_GetMouseFocus() != bd->Window) return;\n    ImGuiMouseCursor imgui_cursor = ImGui::GetMouseCursor();")
platform_replace("if (bd->MouseLastCursor != expected_cursor)" "if (SDL_GetCursor() != expected_cursor)")
set(platform_backend_file "${CMAKE_CURRENT_BINARY_DIR}/imgui_impl_sdl3_anybandui.cpp")
file(CONFIGURE OUTPUT "${platform_backend_file}" CONTENT "${platform_backend}" @ONLY)
