"""Regenerate portable embedded shaders. Ordinary app builds need no shader SDK.

Requires DXC and SPIRV-Cross CLI. See README.md for pinned tool versions.
"""
import argparse
import hashlib
from pathlib import Path
import subprocess
import tempfile

parser = argparse.ArgumentParser()
parser.add_argument("--dxc", required=True)
parser.add_argument("--spirv-cross", required=True)
parser.add_argument("--check", action="store_true", help="Fail if committed shader bytes are stale")
args = parser.parse_args()
root = Path(__file__).resolve().parent
digest = hashlib.sha256(b"".join(p.read_bytes() for p in sorted(root.glob("*.hlsl")))).hexdigest()
output = [f"// Source SHA256: {digest}\n", "// Generated by shaders/build.py. Do not edit.\n#pragma once\n#include <cstddef>\nnamespace crt_shaders {\n"]
with tempfile.TemporaryDirectory() as scratch:
    scratch = Path(scratch)
    for name, stage in (("fullscreen", "vert"), ("blur", "frag"), ("crt", "frag"), ("desaturate", "frag")):
        source = root / f"{name}.{stage}.hlsl"
        profile = "vs_6_0" if stage == "vert" else "ps_6_0"
        common = [args.dxc, str(source), "-T", profile, "-E", "main", "-O3"]
        for fmt in ("dxil", "spirv", "msl"):
            binary = scratch / f"{name}.{fmt}"
            extra = [] if fmt == "dxil" else ["-spirv", "-fspv-target-env=vulkan1.0"]
            subprocess.run(common + extra + ["-Fo", str(binary)], check=True)
            if fmt == "msl":
                metal = scratch / f"{name}.metal"
                subprocess.run([args.spirv_cross, str(binary), "--msl", "--msl-version", "20100", "--msl-decoration-binding",
                                "--output", str(metal)], check=True)
                data = metal.read_bytes() + b"\0"
            else:
                data = binary.read_bytes()
            output.append(f"inline constexpr unsigned char {name}_{fmt}[] = {{\n")
            for offset in range(0, len(data), 24):
                output.append(",".join(str(b) for b in data[offset:offset+24]) + ",\n")
            output.append("};\n")
output.append("}\n")
generated = root / "generated.h"
content = "".join(output)
if args.check:
    if not generated.exists() or generated.read_text(encoding="utf-8") != content:
        raise SystemExit("Generated shader header is stale; run this script without --check")
else:
    generated.write_text(content, encoding="utf-8")
